### ISSUE TITLE
DTDL Version Issue ..V3 is not supporting 

### ISSUE THREAD

**Issue by MaheshDevulapally** [Azure/opendigitaltwins-building#83]
![image](https://user-images.githubusercontent.com/127103543/234216275-254c3858-38e9-4334-9493-c5b9ad187140.png)
while uploading this ontology to digital twin instance it is observed that V3 is not supported only V2 supported ...@context specifier has value 'dtmi:dtdl:context;3', which specifies a DTDL version that exceeds the configured max version of 2.
where can we get V2 repository?

**Comment by hammar** [comment]
[Release 1.0 of of this repo](https://github.com/Azure/opendigitaltwins-building/releases/tag/v1.0) uses DTDL v2, as does the [later REC 4.0 release](https://github.com/RealEstateCore/rec). The latter is hosted in a separate repository and structurally quite evolved from this one (e.g., uses Brick Schema points instead of capabilities, and Brick Schema equipment classes).
